### ISSUE TITLE
ccs_accum_nbad type mismatch

### ISSUE THREAD

**Issue by moocow-the-bovine** [moocow-the-bovine/PDL-CCS#6]
see https://github.com/moocow-the-bovine/PDL-CCS/pull/5#issuecomment-1100614446

- ccs_accum_nbad should get `out_type => 'indx'` rather than `out_type => 'int+'`
- tests for `ccs_accum_nbad` should ensure `$missing->type == $nzvalsIn->type`
- CCS fix should wait until PDL segfaults with current behavior have been dealt with

**Comment by mohawk2** [comment]
Thank you for your extremely thorough attention to this fascinating, subtle problem!

> For the high-level PDL::CCS::Nd wrappers, I think it's always the case that `NNzOut==NnzIn`, so it doesn't make sense there. I can imagine cases with structured data where it does make sense though, and it could be wasteful (especially for ufuncs) to force `NNzOut==NnzIn` there, so I'm inclined to leave those dimensions distinct.

My recommendations are based on what I've learned from investigating this, and also from my recent experience of using a lot of `RedoDimsCode` in PDL::LinearAlgebra so I could just pass in `null` instead of the agonising nonsense with `zeroes`. They are (I removed the ones you've indicated above since you obviously know your library better than I!):
- use `PDL_MAYBE_SIZE` from https://github.com/PDLPorters/pdl-linearalgebra/blob/f789c4100d04ba9d1b50f8c18249bdef29338496/Real/real.pd#L63-L75, for example at https://github.com/PDLPorters/pdl-linearalgebra/blob/f789c4100d04ba9d1b50f8c18249bdef29338496/Real/real.pd#L204-L208 - this only sets the dimsize if the passed ndarray is a `null`
- this would allow you to pass in `null` as the output params but would still allow you to not do so (though, srsly, why)
- set the badflag as desired in the `Code` with `$PDLSTATESETBAD(ndarrayname)`, outside an inserted `broadcastloop` - see https://github.com/PDLPorters/pdl/commit/76f353eef645728f0df59172fcb92f12c6b5344a for examples
- make the `CopyBadStatusCode` just call the `PDL.propagate_badflag` with the set values (i.e. `PDL->propagate_badflag(ndarrayname, !!(ndarrayname->state & PDL_BADVAL));`), i.e. to do the same as the new API does
- just make the `missing` Par be the last value of your `valsIn`, use `RedoDimsCode` to give that a dim of `NnzInPlus1`, and in `loop (NnzInPlus1) %{ %}` use an `if (NnzInPlus1 == $SIZE(NnzInPlus1)-1) break;` at the top to not accidentally process the missing value

I believe with those points, you could heavily reduce the `PMCode` (though not eliminate thanks to the slicing requirement).

**Comment by moocow-the-bovine** [comment]
- ["easy" (= symptomatic) fixes](https://github.com/moocow-the-bovine/PDL-CCS/issues/6#issue-1206064592) applied in 4b653fe , uploaded to CPAN as PDL::CCS v1.23.20
- badflag-handling for ufunc counter-functions (nbad, ngood, nnz) adjusted too (but probably not sufficiently)
- `broadcastloop` and `$PDLSETSTATE*(ndarrayname)` in `Code` appear not to work with my (probably outdated) PDL-2.019 (-> yes, I should upgrade, but am not going to do that right now)
- signature-altering changes, moving dim-checks to `RedoDimsCode` (in a way which is compatible with older PDLs), and minimizing/eliminating `PMCode` are all out of my (TUIT) price range at the moment

... leaving this issue open for now, although I may copy+paste your suggestions (for which many thanks, in particular for the linked examples!) into separate issues later.

**Comment by mohawk2** [comment]
Switching the minimum PDL 2.081, as discussed on #13, will allow using `indx` where appropriate, which will solve the type mismatch issue.

**Comment by moocow-the-bovine** [comment]
> ... leaving this issue open for now, although I may copy+paste your suggestions (for which many thanks, in particular for the linked examples!) into separate issues later.

@mohawk2 
I've made https://github.com/moocow-the-bovine/PDL-CCS/issues/16 for the outstanding overhaul issues.  I think that with your recent https://github.com/moocow-the-bovine/PDL-CCS/pull/15 and https://github.com/moocow-the-bovine/PDL-CCS/commit/2ad95d3a3bd545c8796cd181c964c4653d5c6981 , this issue can be closed.  Feel free to re-open if you disagree.
